src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>General_Comments__c</fullName>
        <label>General Comments</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>JS01__Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Nonprofit</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JS01__Date_Case_Closed__c</fullName>
        <label>Date Case Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JS01__External_Overview__c</fullName>
        <inlineHelpText>A high level summary of the case, appropriate for Pro Bono portal</inlineHelpText>
        <label>External Overview</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>JS01__Pro_Bono_Portal_Status__c</fullName>
        <inlineHelpText>The status of the case on the JusticeServer Portal</inlineHelpText>
        <label>Pro Bono Portal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available - Public</fullName>
                </value>
                <value>
                    <fullName>Available - Private</fullName>
                </value>
                <value>
                    <fullName>Interest Expressed</fullName>
                </value>
                <value>
                    <fullName>Conflict Passed</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JS01__Special_Requirements__c</fullName>
        <inlineHelpText>Indicate any special requirements the volunteer meet in order to take this case</inlineHelpText>
        <label>Special Requirements</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>JS01__Pro_Bono_Portal_Status__c</fullName>
        <label>Pro Bono Portal Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>false</active>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Resource</fullName>
        <active>true</active>
        <label>Resource</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Problem__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Problems</relationshipLabel>
        <relationshipName>Problems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dollar_Amount_for_Revenue_Recovery__c</fullName>
        <label>Dollar Amount for Revenue Recovery</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Eligibility_Outcome_Detail__c</fullName>
        <label>Eligibility Outcome - Detail</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Outcome__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consumer’s application is being processed</fullName>
                </value>
                <value>
                    <fullName>Consumer made eligible for program</fullName>
                </value>
                <value>
                    <fullName>Consumer continued eligibility</fullName>
                </value>
                <value>
                    <fullName>Consumer assessed for appropriate program</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expedited__c</fullName>
        <label>Expedited?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HCA_No_Yes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Member__c</fullName>
        <label>Family Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Problems</relationshipLabel>
        <relationshipName>Problems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Highest_Level_of_Appeal__c</fullName>
        <formula>IF(
   ISPICKVAL(Judicial_Review__c,&quot;Yes&quot;),
   &quot;Judicial Review&quot;,
   IF(
      ISPICKVAL(HHS_Appeal__c,&quot;Yes&quot;),
      &quot;HHS Appeal&quot;,
      IF(
         ISPICKVAL(ALJ_Hearing__c,&quot;Yes&quot;),
         &quot;ALJ Hearing&quot;,
         IF(
            ISPICKVAL(Agency_Appeal__c,&quot;Yes&quot;), 
            &quot;Agency Appeal&quot;,
            IF(
               ISPICKVAL(Grievance_Against_Plan__c,&quot;Yes&quot;),
               &quot;Grievance Against Plan&quot;,
               IF(
                  ISPICKVAL(Informal_Review_with_Plan__c,&quot;Yes&quot;),
                  &quot;Informal Review with Plan&quot;,
                  IF(
                     ISPICKVAL(Escalation_to_Agency__c,&quot;Yes&quot;),
                     &quot;Escalation to Agency&quot;,
                     &quot;No Appeal&quot;
                  )
               )
            )
         )
      )
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Highest Level of Appeal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outcome_Comment_Notes__c</fullName>
        <label>Outcome Comment/Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Outcome_Type__c</fullName>
        <label>Outcome Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>MLP</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Outcome_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>HCA_Outcome</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Outcome_of_Appeal__c</fullName>
        <label>Outcome of Appeal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Granted Client Claim</fullName>
                </value>
                <value>
                    <fullName>Problem resolved after agency escalation</fullName>
                </value>
                <value>
                    <fullName>Favorable Conditional Withdrawal</fullName>
                </value>
                <value>
                    <fullName>Denied Client Claim</fullName>
                </value>
                <value>
                    <fullName>Program declined representation due to lack of merits</fullName>
                </value>
                <value>
                    <fullName>Client withdrew hearing request</fullName>
                </value>
                <value>
                    <fullName>Client Declined Our Services/Loss of Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Problem__c</fullName>
        <formula>CASE(  RecordType.Name  , 
       &apos;Eligibility Problem&apos;,  TEXT( Eligibility_Problem__c ), 
       &apos;MLP Problem&apos;,  TEXT( MLP_Problem__c ) ,
       &apos;Service Problem&apos;, TEXT ( Service_Problem__c ),
 &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Problem</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referred_To_Other__c</fullName>
        <label>Referred To - Other</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referred_To__c</fullName>
        <label>Referred To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Outcome_Detail__c</fullName>
        <label>Service Outcome - Detail</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service authorized</fullName>
                </value>
                <value>
                    <fullName>Service scheduled</fullName>
                </value>
                <value>
                    <fullName>Billing problem resolved</fullName>
                </value>
                <value>
                    <fullName>Plan enrollment/disenrollment confirmed</fullName>
                </value>
                <value>
                    <fullName>Language Barrier Overcome</fullName>
                </value>
                <value>
                    <fullName>Disability Barrier Overcome</fullName>
                </value>
                <value>
                    <fullName>Other Discrm. Overcome</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Problem</label>
    <nameField>
        <displayFormat>Prob-{0000000}</displayFormat>
        <label>Problem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Problems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HCA_CaseCloseController.cls
/***********************************************************************
* Name               : HCA_CaseCloseController                         *
* Description        : JusticeServer - Case Close Screen               *
* Created By         : Techbridge                                      *        
************************************************************************/
public class HCA_CaseCloseController{
    
    public Case caseRecord {get;set;}
    public String caseId;
    public List<CaseStatus> statusList {get;set;}
    public List<SelectOption> statusOption {get;set;}
    public String selectedStatus {get;set;}
    public String monetaryId;
    public String nonMonetaryId;
    public Integer monetaryCounter {get;set;}
    public Integer nonMonetaryCounter {get;set;}
    public Boolean showProblemScreen{get;set;}
    public Boolean showCaseScreen{get;set;}
    public List<Problem__c> problemList {get;set;}
    
    /***************************************************************************
    *@Description : This is the contructor                                     *
    *@Params      : ApexPages.StandardController controller                    *
    *@Return      : Void                                                       *    
    ****************************************************************************/
    public HCA_CaseCloseController(ApexPages.StandardController controller){
        showProblemScreen = true;
        showCaseScreen = false;
        caseId = ApexPages.currentPage().getParameters().get('id');

        //GET CASE STATUS PICKLIST VALUES
        Map<String,String> statusValueLabelMap = new Map<String,String>();
        Schema.DescribeFieldResult fieldResult = Case.Status.getDescribe();
        List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
        
        for( Schema.PicklistEntry v : values) {
            statusValueLabelMap.put(v.getValue(),v.getLabel());
        }
        
        String caseQuery;
        caseQuery = 'SELECT ';
        for(Schema.FieldSetMember fSetMem : SObjectType.Case.FieldSets.JS01__Close_Case_Details.getFields()) {
            caseQuery += fSetMem.getFieldPath() + ',';
        }
        for(Schema.FieldSetMember fSetMem : SObjectType.Case.FieldSets.Close_Case_Summary.getFields()) {
            caseQuery += fSetMem.getFieldPath() + ',';
        }
        caseQuery = caseQuery.removeEnd(',');
        caseQuery = caseQuery + ',IsClosed,Status,CaseNumber,Contact.Name';
        //caseQuery += ',(SELECT Id, Contact__c,Case__c,Contact__r.Pro_Bono_Portal_Status__c, Status__c FROM Resource_Assignments__r)';
        caseQuery += ',(SELECT Id, Name, RecordType.Name,Problem__c,Outcome_Type__c,Outcome__c,Eligibility_Outcome_Detail__c,Service_Outcome_Detail__c,Referred_To__c,Referred_To_Other__c,Outcome_Comment_Notes__c,Dollar_Amount_for_Revenue_Recovery__c,Highest_Level_of_Appeal__c,Outcome_of_Appeal__c,Expedited__c FROM Problems__r)';
        caseQuery += ' FROM Case WHERE Id =: caseId LIMIT 1 FOR UPDATE';
        
        /************************************* EXECUTE QUERY  *******************************/             
        
        System.debug('************** caseQuery' + caseQuery );
        try{
            caseRecord = Database.Query(caseQuery);
            if(caseRecord.JS01__Date_Case_Closed__c == null){
                caseRecord.JS01__Date_Case_Closed__c = System.today();
            }
            statusOption = new List<SelectOption>();
            if(!caseRecord.isClosed){
                statusOption.add(new SelectOption('','--None--'));
            }else{
                if(statusValueLabelMap.containsKey(caseRecord.Status) && statusValueLabelMap.get(caseRecord.Status) != null ){
                    statusOption.add(new SelectOption(caseRecord.Status,statusValueLabelMap.get(caseRecord.Status)));
                }
            }
            if(caseRecord.Problems__r.size() > 0){
                problemList = caseRecord.Problems__r;
            }
            
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'An unexpected error occurred while fetching Case data. Kindly contact Support.'));    
        }  
    }
    
    /***************************************************************************
    *@Description : This method is used to get Case Status Values  that are    * 
    *               - Closed                                                   *
    *@Params      : void                                                       *
    *@Return      : List<SelectOption>                                         *    
    ****************************************************************************/
    public List<SelectOption> getStatusValues(){
        statusList = [SELECT ApiName,MasterLabel,SortOrder FROM CaseStatus WHERE IsClosed = true ORDER BY SortOrder];
        if(statusList != null){
            if(!statusList.isEmpty()){
                for(CaseStatus statusValue : statusList){
                    if(caseRecord.isClosed){
                        if(statusValue.ApiName != caseRecord.Status){
                            statusOption.add(new SelectOption(statusValue.ApiName, statusValue.MasterLabel));
                        }
                    }else{
                         statusOption.add(new SelectOption(statusValue.ApiName, statusValue.MasterLabel));
                    }
                }
            }
        } 
        return statusOption; 
    }
    
    /***************************************************************************
    *@Description : This method delets row from Non Monetary table             * 
    *@Params      : void                                                       *
    *@Return      : void                                                       *    
    ****************************************************************************/
    public PageReference save(){
        PageReference pageRef;
        Boolean showFieldReqdError = false;
        try{
            //CASE
            List<Case> caseRecords = [SELECT 
                                            Id, Subject, Contact.FirstName, JS01__Pro_Bono_Portal_Status__c, JS01__External_Overview__c, JS01__Special_Requirements__c, 
                                            JS01__Client_Type__c, 
                                            Contact.LastName,Account.Name, Contact.MailingStreet, Contact.MailingCity, Contact.MailingState, Contact.MailingPostalCode, 
                                            Account.BillingStreet, Account.BillingCity, Account.BillingState, Account.BillingPostalCode,   
                                            (SELECT Id, JS01__Contact__c,JS01__Case__c,JS01__Contact__r.JS01__Pro_Bono_Portal_Status__c, JS01__Status__c FROM JS01__Resource_Assignments__r)
                                       FROM 
                                            Case 
                                        WHERE 
                                            Id =: caseRecord.Id LIMIT 1];
            //UPDATE RESOURCE ASSIGNMENT STATUS
            if(caseRecord.JS01__Resource_Assignments__r.size() > 0){
                CloseResourceAssignmentsRelatedToCase(caseRecord.JS01__Resource_Assignments__r,'','');
            }
            if(selectedStatus != null){
                caseRecord.Status = selectedStatus;     
                caseRecord.JS01__Pro_Bono_Portal_Status__c = 'Completed';
                caseRecord.JS01__Date_Case_Closed__c = System.Today();            
            }
            
            for(Schema.FieldSetMember fSetMem :  SObjectType.Case.FieldSets.Close_Case_Summary.getFields()) {
                if(fSetMem.getFieldPath() != 'General_Comments__c' && (caseRecord.get(fSetMem.getFieldPath())) == null){
                    if(caseRecord.General_Comments__c == null){
                        showFieldReqdError = true;
                    }
                }
            }
            if(showFieldReqdError){
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Please enter value in first 3 fields or General Comments in Case Summary Section'));
            }
            if(!showFieldReqdError){
                update problemList;
                update caseRecord;
                pageRef = new PageReference('/'+caseRecord.Id);
                pageRef.setRedirect(true);
            }

        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error at Line : '+ e.getLineNumber() + ', Error Message : ' +  e.getMessage()));    
        }
        return pageRef;
    }   
    
    /***************************************************************************
    *@Description : This method is used to CLOSE RESOURCE ASSIGNMENT           *
    *@Params      : Void                                                       *
    *@Return      : Void                                                       *    
    ****************************************************************************/
    public static void CloseResourceAssignmentsRelatedToCase(List<JS01__Resource_Assignment__c> assignmentsRelatedToCase,string comments,string reason){
        System.Debug('2222>>>>'+assignmentsRelatedToCase);
        Set<String> contactIds = new Set<String>();
        if(assignmentsRelatedToCase.size() > 0){
            for(JS01__Resource_Assignment__c ra : assignmentsRelatedToCase){
                System.Debug('3333>>>>'+ra.JS01__Contact__c);
                if(ra.JS01__Contact__c != null){
                    contactIds.add(ra.JS01__Contact__c);
                }
            }
        }
        
        if(assignmentsRelatedToCase.size() > 0){
            for(JS01__Resource_Assignment__c ra : assignmentsRelatedToCase){
                System.debug(ra.JS01__Contact__c + '!!!!' + (ra.JS01__Contact__c != null && (ra.JS01__Status__c == 'Pending_Acceptance' || ra.JS01__Status__c == 'Active')));
                if(ra.JS01__Contact__c != null && (ra.JS01__Status__c == 'Pending_Acceptance' || ra.JS01__Status__c == 'Active')){
                    ra.JS01__Status__c = 'Closed';
                    if(!String.IsBlank(comments))
                        ra.JS01__Closing_Comments__c = comments;
                    if(!String.IsBlank(reason))
                        ra.JS01__Reason_for_Closing__c = reason;
                }
            }
            update assignmentsRelatedToCase;
        }
    }
   
    /***************************************************************************
    *@Description : This is the NEXT Button action                             *
    *@Params      : Void                                                       *
    *@Return      : Void                                                       *    
    ****************************************************************************/
    public PageReference next(){
        showProblemScreen = false;
        showCaseScreen = true;
        return null;
    } 
    
    /***************************************************************************
    *@Description : This is the PREVIOUS Button action                         *
    *@Params      : Void                                                       *
    *@Return      : Void                                                       *    
    ****************************************************************************/
    public PageReference previous(){
        showProblemScreen = true;
        showCaseScreen = false;
        return null;
    }  
    
    /***************************************************************************
    *@Description : This is the CANCEL Button action                           *
    *@Params      : Void                                                       *
    *@Return      : Void                                                       *    
    ****************************************************************************/
    public PageReference cancel(){
        PageReference pageRef = new PageReference('/'+caseRecord.Id);
        pageRef.setRedirect(true);
        return pageRef;
    } 
}//End of Class